---

###
### Enable sudo (required for docker service)
###
sudo: required


###
### Language
###
language: minimal


###
### What operating systems to test on
###
os:
  - linux
  - osx


###
### Install requirements
###
install:
  - retry() {
      for ((n=0; n<60; n++)); do
        echo "[${n}] ${*}";
        if eval "${*}"; then
          return 0;
        fi;
        sleep 1;
      done;
      return 1;
    }


###
### Linting
###
before_script:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      retry make lint;
    fi


###
### Testing
###
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      retry make test;
    else
      retry make test ARGS=1;
    fi
